### PR TITLE
Updated URL to resources

### PR DESCRIPTION
**Pull request by jmachuca77**
Updated the URLs so that they point to valid resources

### CODE REVIEW

**Comment by jmachuca77** [comment]
This addresses part of the issues in ardupilot/ardupilot#12624

**Comment by rmackay9** [comment]
shouldn't we put this on the firmware.ardupilot.org site?  I'm a bit worried about links to locations with no clear owner.

**Comment by jmachuca77** [comment]
Probably... but I don't have access to that, and this is how it has been for ever. So I just fixed the link to the file.

**Comment by rmackay9** [comment]
OK, a bit outside my area but merging!

**Pull request merged**
